version: '3.9'

services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - "127.0.0.1:{{ app_port }}:2368"
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: https://{{ app_fqdn }}/
    volumes:
      - ./data/ghost:/var/lib/ghost/content
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ghost
    volumes:
      - ./data/mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 384M
